name: Add-on Validations

on:
  push:
    branches: [ master, main, official_repository, official_repository_matrix ]

  pull_request:
    branches: [ master, main, official_repository, official_repository_matrix ]

jobs:

  addon-validations:
    if: github.repository == 'anxdpanic/plugin.video.composite_for_plex'

    runs-on: ubuntu-latest

    name: Add-on Validations

    steps:
      - name: Set up Python v3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Checkout kodi-addon-checker
        uses: actions/checkout@v2
        with:
          repository: xbmc/addon-check
          path: addon-check

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install arrow
          python -m pip install requests
          python -m pip install isort
          python -m pip install pylint
          python -m pip install addon-check/

      - name: Staging
        run: |
          rm -rf LICENSES/
          rm -f .gitattributes
          cp -t ${HOME} .pylintrc
        working-directory: ${{ github.event.repository.name }}

      - name: Set KODI_BRANCH to jarvis
        if: endsWith(github.ref, '/master') || github.event.pull_request.base.ref == 'master'
        run: |
          echo "KODI_BRANCH=jarvis" >> $GITHUB_ENV

      - name: Set KODI_BRANCH to leia
        if: endsWith(github.ref, '/official_repository') || github.event.pull_request.base.ref == 'official_repository'
        run: |
          echo "KODI_BRANCH=leia" >> $GITHUB_ENV

      - name: Set KODI_BRANCH to matrix
        if: endsWith(github.ref, '/official_repository_matrix') || github.event.pull_request.base.ref == 'official_repository_matrix'
        run: |
          echo "KODI_BRANCH=matrix" >> $GITHUB_ENV

      - name: Kodi Add-on Checker
        id: kodi-addon-checker
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=${KODI_BRANCH}

      - name: Pylint
        id: pylint
        run: |
          pylint resources/lib/
        working-directory: ${{ github.event.repository.name }}

      - name: isort
        id: isort
        run: |
          isort --force-single-line-imports . --diff
        working-directory: ${{ github.event.repository.name }}
