name: Add-on Validations

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:

  addon-validations:
    if: github.repository == 'anxdpanic/plugin.video.composite_for_plex'

    name: Add-on Validations
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout Add-on
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install arrow
          python -m pip install requests
          python -m pip install isort
          python -m pip install pylint
          python -m pip install git+https://github.com/xbmc/addon-check.git

      - name: Kodi Add-on Checker (Nexus)
        id: kodi-addon-checker-jarvis
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=nexus
        continue-on-error: true

      - name: Pylint
        id: pylint
        run: |
          cp -t ${HOME} .pylintrc
          pylint resources/lib/
        continue-on-error: true
        working-directory: ${{ github.event.repository.name }}

      - name: isort
        id: isort
        run: |
          isort --force-single-line-imports . --diff
        continue-on-error: true
        working-directory: ${{ github.event.repository.name }}
