# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ action-test ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: project

    - name: Checkout sync_addon_metadata_translations
      uses: actions/checkout@v2
      with:
        repository: anxdpanic/sync_addon_metadata_translations
        path: sync_addon_metadata_translations
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install sync_addon_metadata_translations/
    
    - name: Delete old PR branch
      run: |
        git branch -d sync_localization_metadata
      continue-on-error: true
      working-directory: ./project

    - name: Create PR branch
      run: |
        git branch sync_localization_metadata
        git checkout sync_localization_metadata
      working-directory: ./project

    - name: Sync localization metadata
      run: |
        sync-addon-metadata-translations
      working-directory: ./project
